name: CI

on:
    pull_request:
        branches: ['master', 'stable']
    push:
        branches: ['master', 'stable']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '14'
            - name: Install Dependencies
              run: yarn install
            - name: Lint
              run: yarn lint
            - name: Format
              run: yarn format:check
